
spring:
  h2:
    console:
      enabled: true  # Habilita o console H2 para acesso à interface web
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb  # URL de conexão com o banco de dados H2 em memória
    username: sa  # Nome de usuário
    password:  # Senha (deixe em branco)

  # Configuração do Hibernate
  hibernate:
    ddl-auto: update  # Estratégia para atualizar o esquema do banco de dados
    show-sql: true  # Mostrar consultas SQL no console

server:
  port: 8080  # Porta em que o aplicativo será executado
